routes/web.php
<?php

Route::get('/maintenance', 'MaintenanceController@index')->name('maintenance');

Route::get('/', 'VerificationController@index')->name('verification.index');

Route::get('/profile', 'LawyerProfileController@index')->name('frontend.profile');
Route::post('/profile/edit', 'LawyerProfileController@update')->name('profile.update');
Route::post('/profile/password', 'LawyerProfileController@changePassword')->name('profile.changePassword');


Route::get('/logout', function () {
    Auth::logout();
    return redirect()->route('verification.index');
});
//overrider defaut register
//Route::get('/register','RegistrationController@index')->name('register');

Auth::routes();

Route::get('/home', function(){
  if(!( $user = auth()->user() ) ) return redirect('/');

    $route = $user->role == 'lawyer' ? 'frontend.index' : 'backend.index';

    return redirect()->route($route);

});

Route::get('/manager', 'BackendController@index')->name('backend.index');
Route::get('/manager/all-requests', 'BackendController@showPaginatedRequests')->name('all-requests');
Route::get('/all-requests-data', 'BackendController@AllRequests')->name('all-requests-data');
Route::post('/export-requests', 'BackendController@exportRequests');
Route::get('/export-reports', 'BackendController@exportReports');
// Route::get('/');
Route::get('/exports/today', 'BackendController@exportToday')->middleware('auth');

Route::get('/terms-and-conditions', 'TermConditionController@index')->name('terms-conditions');

require_once 'stamp-request-routes.php';
require_once 'profile-routes.php';
require_once('ticket-routes.php');
require_once('verification-routes.php');
require_once('ticket-routes.php');
require_once('backend-ticket-routes.php');
require_once('registration-routes.php');
require_once('get-lawyer-routes.php');

app/StampRequest.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class StampRequest extends Model
{
  use SoftDeletes;

    protected $with = ['buyer'];
    protected $guarded = [];
    protected $appends = ['details', 'buyer_name', 'branch', 'scn', 'total_cost'];
    protected $dates = ['deleted_at'];
    public function getDetailsAttribute()
    {
      $string = sprintf("%s %s, %s %s, %s",
                         $this->packs,
                         str_plural('Pack', $this->packs),
                         $this->sheets,
                         str_plural('Sheet', $this->sheets),
                         $this->type
              );
      return $string;
    }


    public function buyer()
    {
      return $this->belongsTo('App\User' , 'buyer_id');
    }


    public function getBuyerNameAttribute()
    {
      return $this->buyer->name;
    }


    public function getScnAttribute()
    {
      return $this->buyer->lawyer_account->scn;

    }


    public function getBranchAttribute()
    {
      return $this->buyer->lawyer_account->branch;
    }


    public function setPaid($transaction_id)
    {
      $this->update([
        'paid' => true,
        'paid_at' => now()->toDateTimeString(),
        'transaction_id' => $transaction_id,
        'status' => 'confirmed'
        ]);
    }


    public function getIsPaidAttribute()
    {
      return ! is_null($this->paid_at);
    }

    public function getPaymentUrlAttribute()
    {
      return url('/stamp-request-payment/'.$this->id);
    }


    public function getInvoiceUrlAttribute()
    {
      return url('/stamp-request-invoice/'.$this->id);
    }


    public function scopeUnpaid($query)
    {
      return $query->whereNull('paid_at');
    }

    public function getTotalCostAttribute()
    {
      return (int) ($this->amount + $this->charges);
    }
}

app/Http/Controllers/FrontendController.php
<?php

namespace App\Http\Controllers;

use App\StampRequest;
use Illuminate\Http\{Request, Response};

class FrontendController extends Controller
{
function __construct()
{
  $this->middleware('auth');
}
    public function index( Request $request )
    {
      $stamp_requests = auth()->user()->stampRequests;
      $totalTickets = auth()->user()->ticket;
      $unpaid_requests = count($stamp_requests->where('paid', false));
      $total_stamps = count($stamp_requests);
      $total_stamps =  ($total_stamps > 0 ) ? $total_stamps : 1 ;
      $stamp_requests_count =  ( $stamp_requests->count() > 0 ) ? $stamp_requests->count() : 1 ;
      $percentage = ( $unpaid_requests  / $stamp_requests_count ) * 100 ;
      $pendingTickets = count($totalTickets->whereIn('status',['Pending','New']));
      $totalTickets = count($totalTickets);
      //dd($pendingTickets);
      return view('frontend.buyer-home', compact('stamp_requests','totalTickets','pendingTickets', 'percentage'));
    }

    public function buyerRequests(Request $request, Response $response)
    {
      $requests = auth()->user()->stampRequests;
      $cart = $requests->where('paid', false)->first();
      $stamp_requests = $requests->where('paid', true);
      return view('frontend.buyer-request', compact('stamp_requests', 'cart'));
    }

}

resources/views/frontend/buyer-request.blade.php
@extends('layouts.frontend.main')
@section('title','Dashboard')
@prepend('styles')
<!-- Custom CSS  -->
<link href="assets/node_modules/morrisjs/morris.css" rel="stylesheet">
<!--Toaster Popup message CSS -->
<link href="assets/node_modules/toast-master/css/jquery.toast.css" rel="stylesheet">
<style>
  .label-processing {
    background-color: #fb9678;
    border-color: #fb9678;
    border-color: #dee2e6;
  }

  .label-confirmed,
  .label-unconfirmed {
    color: #212529;
    background-color: #f8f9fa;
  }
  .label-shipped {
    background-color: #00c292;
    border-color: #00c292;
  }
  .label-paid {

  }
  .label-unpaid {

  }
</style>
@endprepend

@section('content')
<!-- Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->
<div class="row page-titles">
  <div class="col-md-5 align-self-center">
    <h4 class="text-themecolor">My Request</h4>
  </div>
  <div class="col-md-7 align-self-center text-right">
    <div class="d-flex justify-content-end align-items-center">
      <ol class="breadcrumb">
        <li class="breadcrumb-item active">Dashboard</li>
      </ol>
    </div>
  </div>
</div>
<div class="col-12" id="app">
  <div class="card">
    <div class="card-body">
      <h4 class="card-title">My Requests</h4>
      <h6 class="card-subtitle mt-2 mb-4"> This is a listing of all your requests, from here you can make payments for a purchase, view the invoice/reciept for a purchase or view its status.</h6>
      <div class="table-responsive">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>Details</th>
              <th>Status</th>
              <th>Date</th>
              <th class="text-nowrap">Action</th>
            </tr>
          </thead>
          <tbody>
            @forelse($stamp_requests as $request)
            <tr>
              <td>
                {{$request->details}}
                <h6 class="text-success text-bold pull-right">
                  {{naira($request->amount/100)}}
                  <small>
                    (&plus; {{naira($request->charges/100)}} charges )
                  </small>
                </h6>
              </td>
              <td>
                <span class="label label-{{ $request->paid ? 'success' : 'danger'}}">{{ $request->paid ? 'paid' : 'unpaid'}}</span>
                <span class="label label-{{$request->status}}">{{$request->status}}</span>
              </td>
              <td>{{ $request->created_at->toFormattedDateString()}}</td>
              <td class="text-nowrap">
                <a href="{{ $request->invoice_url}}" data-toggle="tooltip" data-original-title="View Invoice"> <i class="mdi mdi-ticket-confirmation text-inverse m-r-10"></i> </a>
                @unless($request->paid)
                <a href="{{ $request->payment_url}}" data-toggle="tooltip" data-original-title="Make Payment"> <i class="mdi mdi-wallet text-success"></i> </a>
                @endunless
              </td>
            </tr>
            @empty
            <tr>
              <td colspan="4" class="text-center h3 font-weight-bold">Sorry, there are no requests at this time</td>
            </tr>
            @endforelse
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="col-xs-12">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">
          <i class="mdi mdi-cart text-success"></i>
          My Cart
          </h4>
        <h6 class="card-subtitle mt-2 mb-4">
          This shows your uncompleted requests.
        </h6>
          @if($cart)
            <app-cart :request="{{$cart}}" />
          @endif
        </div>
      </div>
      <flash message="{{ session('message') }}"></flash>

  </div>
</div>
  @endsection

  @push('scripts')
    <script src="{{asset('js/manifest.js')}}"></script>
    <script src="{{asset('js/vendor.js')}}"></script>
    <script src="{{asset('js/app.js')}}"></script>
  @endpush

resources/views/frontend/landing.blade.php
@extends('layouts.frontend.landing')
@push('styles')

@endpush


@section('content')
<!-- Navigation -->
    <nav class="navbar navbar-light bg-light static-top">
      <div class="container">
        <a class="navbar-brand" href="{{ route('verification.index') }}">
          <img src="{{ asset('img/logo.png') }}" width="70" class="img-responsive">
         </a>

        <div class="navbar-right">
          <a href="{{route('login')}}" class="btn btn-info"> Login</a>
          <a href="{{route('register')}}" class="btn btn-info"> Register</a>
        </div>
        


      </div>
    </nav>

    <!-- Masthead -->
    <header class="masthead text-white text-center">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <h2 class="mb-5">Welcome to NBA Stamp Purchase Portal</h2>
          </div>
          <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
          <form method="post" id="search" action="{{route('nba.show')}}">
                @csrf
              <div class="form-row" style="">
                <div class="col-12 col-md-9 mb-2 mb-md-0">
                    {{-- pattern="[A-Za-z0-9]{6,9}" --}}
                  <input type="text" name="scn" id="scn" class="form-control form-control-lg"  placeholder="Enter your SCN (SCN123456)..." required="required" />
                </div>
                <div class="col-12 col-md-3">
                  <button type="submit" class="btn btn-block btn-lg btn-default search"><i class="glyphicon glyphicon-search"></i> Submit</button>
                </div>
              </div>
			     </form>

      			  <div class="col-12 result" style="display:none">
      				  <div style=" margin:auto;">
                  <h4 id="lawyer-name"> </h4>
      					  <div style="margin-top: 20px;">
                    <a id="continue" class="btn btn-info pull-right" style="display:none; margin-right: 20px;"> Continue</a>
                  <a href="{{route('register')}}" id="contact" class="btn pull-right" style="margin-right: 20px; background-color: #ff9118; color: white;"> Contact Support</a>
                  
                  <button class="btn btn-danger close-result"> Cancel</button>
                  </div>
      				</div>
      			</div>
          </div>
        </div>
      </div>
    </header>
@endsection

@push('scripts')
<script>
    $(document).ready(function(){



  $('#continue').on('click',function(){
    window.location = $(this).attr('href');
  })

	$('#search').on('submit',function(e){
    e.preventDefault();
    $('.search').text('Processing...').attr('disabled', true);
    //loadingform
    $form = $(this);
    var action = $form.attr('action');
    var formData =$form.serialize();
    $.ajax({
        type: 'POST',
        url : action,
        data : formData,
        success : function(data){
            if(!data.error){
                //console.log(data['first_name']);

                var name = data['first_name'] +' '+data['middle_name']+' '+ data['last_name'];
                var scn =  data['scn'];
                $('#contact').hide();
                $('#continue').attr('href', `verification/${data['scn']}`).show();

                //$('#lawyer-name').empty();

               showSearchResult(name);
                //no record found
            }else{
              //data=[];
              $('#continue').hide()
              $('#contact').show();
                showSearchResult('No record found');
            }
        },
        error: function(){
            showSearchResult('Error Occured, Please try again !!');
        }
    });

});

function showSearchResult(result){
  $('#lawyer-name').html(result);
  $('.form-row').hide('slow');
  $('.result').show('slow');
}

$('.close-result').on('click',function(){
  $('#search')[0].reset();
   $('.search').text('Submit').attr('disabled', false);

  $('.result').hide('slow');
  $('.form-row').show('slow');
});

});//end document.ready

//$('#continue').on('click')
    //window.location =


</script>
@endpush

resources/views/frontend/profile.blade.php
@extends('layouts.frontend.main')
@section('title','Profile')
@prepend('styles')
<!-- Custom CSS  -->
    <link href="{{ asset('assets/node_modules/sweetalert/sweetalert.css')}}" rel="stylesheet" type="text/css">

@endprepend

@section('content')

<div class="row page-titles">
                    <div class="col-md-5 align-self-center">
                        <h4 class="text-themecolor">Profile</h4>
                    </div>
                    <div class="col-md-7 align-self-center text-right">
                        <div class="d-flex justify-content-end align-items-center">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{route('frontend.index')}}">Home</a></li>
                                <li class="breadcrumb-item active">Profile</li>
                            </ol>

                        </div>
                    </div>
                </div>
                <!-- ============================================================== -->
                <!-- End Bread crumb and right sidebar toggle -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- Start Page Content -->
                <!-- ============================================================== -->
                <!-- Row -->
                <div class="row">
                    <!-- Column -->
                    <div class="col-md-12">
                        <div class="row mb-4 pt-2 pl-2">
                            <div class="col-sm-8 ">
                                @if($flash = session('alert'))
                                    @include('partials.alert')
                                @endif
                            </div>
                        </div>
                    </div>

                    @php
                    $name = Auth::user()->name;
                    $avatar_url = Auth::user()->avatar_url;
                    $email = Auth::user()->email;
                    $phone_number = $lawyer->phone_number;
                    $branch = $lawyer->branch;
                    $year = $lawyer->year;
                    @endphp


                    <div class="col-lg-4 col-xlg-3 col-md-5">
                        <div class="card">
                            <div class="card-body">
                                <center class="m-t-30"> <img src="{{ $avatar_url }}" class="img-circle" width="150" />
                                    <h4 class="card-title m-t-10">{{$name}}</h4>
                                    <div class="row text-center justify-content-md-center">
                                        <div class="col-4">
                                        	<a href="javascript:void(0)" class="link"> Total Tickets
                                        		<i class="mdi mdi-comment-text-outline"></i>
                                        		<font class="font-medium">{{$tickets}}</font>
                                        	</a>
                                        </div>
                                        <div class="col-4">
                                        	<a href="javascript:void(0)" class="link"> Total Purchase
                                                <i class="mdi mdi-chart-bar"></i> <font class="font-medium">{{$stamps}}</font>
                                        	</a>
                                        </div>
                                    </div>
                                </center>
                            </div>
                            <div>
                                <hr> </div>
                            <div class="card-body">
                            	<small class="text-muted">Email address </small>
                                <h6>{{$email}}</h6> <small class="text-muted p-t-30 db">Phone</small>
                                <h6>{{$phone_number}}</h6> <small class="text-muted p-t-30 db">Branch</small>
                                <h6>{{$branch}}</h6>
                                <br/>

                            </div>
                        </div>
                    </div>
                    <!-- Column -->
                    <!-- Column -->
                    <div class="col-lg-8 col-xlg-9 col-md-7">
                        <div class="card">
                            <!-- Nav tabs -->
                            <ul class="nav nav-tabs profile-tab" role="tablist">

                                <li class="nav-item"> <a class="nav-link" data-toggle="tab" href="#edit-profile" role="tab">Profile</a> </li>
                                <li class="nav-item"> <a class="nav-link" data-toggle="tab" href="#change-password" role="tab">Change Password</a> </li>
                            </ul>
                            <!-- Tab panes -->
                            <div class="tab-content">

                                <!--second tab-->

                                <div class="tab-pane active" id="edit-profile" role="tabpanel">
                                    <div class="card-body">
                                        <form class="form-horizontal form-material" method="post" action="{{route('profile.update')}}">
                                            @csrf
                                            <div class="form-group">
                                                <label class="col-md-12">Full Name</label>
                                                <div class="col-md-12">
                                                    <input type="text" placeholder="{{$name}}" class="form-control form-control-line" disabled="disabled">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="example-email" class="col-md-12">Email</label>
                                                <div class="col-md-12">
                                                    <input type="email" class="form-control form-control-line" name="email" id="email" value="{{$email}}">
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <label class="col-md-12">Phone No</label>
                                                <div class="col-md-12">
                                                    <input type="text" name="phone_number" id="phone_number" class="form-control form-control-line" value="{{$phone_number}}">
                                                </div>
                                            </div>


                                            <div class="form-group">
                                                <div class="col-sm-12">
                                                    <button class="btn btn-success">Update Profile</button>
                                                </div>
                                            </div>

                                        </form>
                                    </div>
                                </div>

                                <div class="tab-pane" id="change-password" role="tabpanel">
                                    <div class="card-body">
                                        <form class="form-horizontal form-material ajaxForm"  method="post" action="{{route('profile.changePassword')}}">
                                            @csrf
                                            <div class="form-group">
                                                <label class="col-md-12">Current Password</label>
                                                <div class="col-md-12">
                                                    <input type="password" name="current-password" id="current-password" class="form-control form-control-line" required="required">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-md-12">New Password</label>
                                                <div class="col-md-12">
                                                    <input type="password" name="new-password" id="new-password" class="form-control form-control-line" required="required">
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <label class="col-md-12">Confirm Password</label>
                                                <div class="col-md-12">
                                                    <input type="password" name="confirm-password" id="confirm-password" class="form-control form-control-line" required="required">
                                                </div>
                                            </div>


                                            <div class="form-group">
                                                <div class="col-sm-12">
                                                    <button class="btn btn-warning">Change Password </button>
                                                </div>
                                            </div>


                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Column -->
                </div>
                <!-- Row -->


@endsection

@push('scripts')
<!--morris JavaScript -->
    <script src="{{ asset('assets/node_modules/raphael/raphael-min.js')}}"></script>
    <script src="{{ asset('assets/node_modules/sticky-kit-master/dist/sticky-kit.min.js')}}"></script>
    <script src="{{ asset('assets/node_modules/sparkline/jquery.sparkline.min.js')}}"></script>
    <script src="{{ asset('assets/node_modules/sweetalert/sweetalert.min.js')}}"></script>

    <script src="{{asset('js/script.js')}}"></script>

    <!--Custom JavaScript -->
@endpush

resources/views/frontend/terms-and-conditions.blade.php
@extends('layouts.frontend.landing')
@push('styles')
<style type="text/css">
	p{
		text-align: justify;
	}
</style>
@endpush


@section('content')
   <nav class="navbar navbar-light bg-light static-top">
      <div class="container">
        <a class="navbar-brand" href="{{ route('verification.index') }}">
          <img src="{{ asset('img/logo.png') }}" width="70" class="img-responsive">
         </a>

        <div class="navbar-right">
          <a href="{{route('verification.index')}}" class="btn btn-info"> Home</a>
        </div>
        


      </div>
    </nav>

    <div class="container" style="min-height: 400px; margin-top: 50px;">
    	<div class="row">
    		<div class="col-md-8 col-lg-offset-2">

    			<h2>Terms and Conditions</h2>
    			<div class="col-lg-12">
    				<h3>Privacy Policy</h3>
    				<p>
    					nbaportal.org.ng respects and protects the privacy of the individuals that access the information and use the services provided through them. Individually identifiable information about the User is not willfully disclosed to any third party without first receiving the User's permission, as covered in this Privacy Policy.
    				</p>
    				<p>
    					This Privacy Policy also covers our treatment of personally identifiable information collected from Sub-Merchants who use or may want to use our payment gateway services, as well as consumer information that we acquire in the course of our business. This Policy also covers the treatment of personally identifiable information that nbaportal.org.ng's back end technology providers / partners may share with it.

    				</p>
    			</div>

    			<div class="col-lg-12">
    				<h3>Disclaimers</h3>
    				<h4> 1. Terms Of Use - General    					
    				</h4>
    				<p>
    					Access to and use of nbaportal.org.ng is provided subject to these conditions. Use of this Site constitutes acceptance of these conditions. If these conditions are not accepted fully, the use of this Site must be terminated immediately.
    				</p>
    				<P>
    					nbaportal.org.ng has made reasonable efforts to secure accuracy of the information provided at this Site and accepts no responsibility/liability for any inadvertent inaccuracies or omissions in this Site. nbaportal.org.ng is at liberty to make changes in the products & services. As far as practicable, reasonable notice of the same will be posted on the site.
    				</P>
    				<P>
    					nbaportal.org.ng does not warrant or represent that the information or materials (including but not limited to the documents and related graphics) available at or from this site are accurate or suitable or reliable or that the site will be free of errors, viruses, bugs, problems or other limitations.
    				</P>
    				<p>
    					Users agree and undertake not to disturb the normal operation of this Site, not to infringe the integrity of this Site by hacking or altering the information contained in this Site, not to prevent or limit access to this Site to other Users, or otherwise.
    				</p>

    			</div>

    			<div class="col-lg-12">
    				<h3>2. Use Of Services</h3>
    				<p>
    					The registered Users may use the services to access any permitted User Account & to conduct transactions as may be permitted with respect to any such User Account. The User agrees to follow instructions of nbaportal.org.ng in effect from time to time with respect to use of the Services.
    				</p>

    				<p>
    					When a user account is used to conduct any Transaction, the authorization given at the time of the Transaction will be treated as if it was given by the User in person, and the User agrees to be bound by each such transaction.
    				</p>
    			</div>

    			<div class="col-lg-12">
    				<h3>3. Transaction Verifications And Records</h3>
    				
    				<p>
    					nbaportal.org.ng's records of each Transaction, and its accounting records, will be deemed to be correct, and will be conclusive and binding upon the User. If the User believes that nbaportal.org.ng records contain an error or omission, the User must give written notice of the suspected error or omission to nbaportal.org.ng within 15 days of the Transaction date.
    				</p>
    			</div>


    		</div>
    	</div>
    </div> 
@endsection